name: "SparkyFitness"
version: "0.1.6"
slug: "sparkyfitness"
description: "Self-hosted fitness, nutrition, water and health tracking"
url: "https://github.com/tsrattan/ha-sparkyfitness"

arch:
  - amd64

startup: application
boot: auto
init: true
stage: experimental
ports:
  80/tcp: 3004

ports_description:
  80/tcp: "SparkyFitness Web UI"

webui: "http://[HOST]:[PORT:80]"
watchdog: "http://[HOST]:[PORT:80]/"


options:
  frontend_url: ""
  extra_trusted_origins: ""
  timezone: "Etc/UTC"
  log_level: "ERROR"
  nginx_rate_limit: "5r/s"
  force_email_login: true

schema:
  frontend_url: str?
  extra_trusted_origins: str?
  timezone: str
  log_level: list(ERROR|WARN|INFO|DEBUG)
  nginx_rate_limit: str
  force_email_login: bool
